### PR TITLE
Implement card 'Twilight Drake' (EX1_043)

### PR DESCRIPTION
**Pull request by 95D**
feat(card-impl): Implement Card 'Twilight Drake' (EX1_043)
feat(task-impl): Implement Task 'Get Hand Cards Num Task'
* I found a problem that causes segfault when unit test.
it seems to be problem calling method "Add Enchant" multiple time with parameters "inline static variable"  (example AddHealthScriptTag, AddAttackScriptTag, etc.. ) while generate card power set,
so that I think about that need to change it inline function, but I have not sure.
just so first i do implement power using effect by construction (::= Effect(GameTag::HEALTH, EffectOperator::ADD, 0) ).
------
fix(rebase): and some more commit to solving a conflict.

### CODE REVIEW

**Comment by utilForever** [comment]
@95D You should fix code first to build it.

**Comment by 95D** [comment]
Sorry. I'm doing it. 
._.) a

**Comment by 95D** [comment]
I'm so sorry for that can't fix it now because I should waste time for my part time job.
I will fix it when my break time (2~3 hour later)
,_,)a

**Comment by utilForever** [comment]
@95D Okay. :)

**Comment by 95D** [comment]
You must be genius.. Do I have something fix?
,_,)c

**Comment by utilForever** [comment]
@95D Nope. That’s enough. :)

**Comment by 95D** [comment]
._.)b

**Pull request merged**
